# Generated by Django 2.1.8 on 2019-09-19 19:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('firstName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('iban', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Iban')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Modificación')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('userCreated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PartnerUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
