# Generated by Django 2.1.8 on 2019-09-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userBank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='firstName',
            new_name='surnames',
        ),
    ]
